// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
import 'package:flutter/foundation.dart'
import 'package:flutter/material.dart'
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR8yLEHRpMtmYX1iEe-g8oo7wEzeWK9uk',
    appId: '1:290145684727:web:00f736565f5369cdef17f2',
    messagingSenderId: '290145684727',
    projectId: 'blooddonation-6d3d4',
    authDomain: 'blooddonation-6d3d4.firebaseapp.com',
    storageBucket: 'blooddonation-6d3d4.firebasestorage.app',
    measurementId: 'G-Z6QFXTTFTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXJFLGU7UFNFrZTaPDP2tZQr4GD_wo42E',
    appId: '1:290145684727:android:ace19b7efbb3700bef17f2',
    messagingSenderId: '290145684727',
    projectId: 'blooddonation-6d3d4',
    storageBucket: 'blooddonation-6d3d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAteJlxOwLG_AqM54UBunwUXlblQjbRd4U',
    appId: '1:290145684727:ios:0c96ed237f997969ef17f2',
    messagingSenderId: '290145684727',
    projectId: 'blooddonation-6d3d4',
    storageBucket: 'blooddonation-6d3d4.firebasestorage.app',
    iosBundleId: 'com.example.blood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAteJlxOwLG_AqM54UBunwUXlblQjbRd4U',
    appId: '1:290145684727:ios:0c96ed237f997969ef17f2',
    messagingSenderId: '290145684727',
    projectId: 'blooddonation-6d3d4',
    storageBucket: 'blooddonation-6d3d4.firebasestorage.app',
    iosBundleId: 'com.example.blood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR8yLEHRpMtmYX1iEe-g8oo7wEzeWK9uk',
    appId: '1:290145684727:web:0913d66cd2bfcbc4ef17f2',
    messagingSenderId: '290145684727',
    projectId: 'blooddonation-6d3d4',
    authDomain: 'blooddonation-6d3d4.firebaseapp.com',
    storageBucket: 'blooddonation-6d3d4.firebasestorage.app',
    measurementId: 'G-G6GTH2R7N2',
  );
}
